# Generated by Django 4.1.4 on 2022-12-27 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('amount', models.IntegerField()),
                ('address', models.CharField(max_length=256)),
                ('payment_type', models.CharField(max_length=256)),
                ('date_of_receipt', models.DateField()),
                ('shelf_life', models.DateField()),
                ('contact_number', models.CharField(max_length=12)),
                ('contact_name', models.CharField(max_length=64)),
            ],
        ),
    ]
